#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-py_cpuinfo
Version  : 8.0.0
Release  : 6
URL      : https://files.pythonhosted.org/packages/e6/ba/77120e44cbe9719152415b97d5bfb29f4053ee987d6cb63f55ce7d50fadc/py-cpuinfo-8.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/e6/ba/77120e44cbe9719152415b97d5bfb29f4053ee987d6cb63f55ce7d50fadc/py-cpuinfo-8.0.0.tar.gz
Summary  : Get CPU info with pure Python 2 & 3
Group    : Development/Tools
License  : MIT
Requires: pypi-py_cpuinfo-bin = %{version}-%{release}
Requires: pypi-py_cpuinfo-license = %{version}-%{release}
Requires: pypi-py_cpuinfo-python = %{version}-%{release}
Requires: pypi-py_cpuinfo-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
==========
        
        
        Py-cpuinfo gets CPU info with pure Python. Py-cpuinfo should work
        without any extra programs or libraries, beyond what your OS provides.
        It does not require any compilation(C/C++, assembly, et cetera) to use.
        It works with Python 2 and 3.

%package bin
Summary: bin components for the pypi-py_cpuinfo package.
Group: Binaries
Requires: pypi-py_cpuinfo-license = %{version}-%{release}

%description bin
bin components for the pypi-py_cpuinfo package.


%package license
Summary: license components for the pypi-py_cpuinfo package.
Group: Default

%description license
license components for the pypi-py_cpuinfo package.


%package python
Summary: python components for the pypi-py_cpuinfo package.
Group: Default
Requires: pypi-py_cpuinfo-python3 = %{version}-%{release}

%description python
python components for the pypi-py_cpuinfo package.


%package python3
Summary: python3 components for the pypi-py_cpuinfo package.
Group: Default
Requires: python3-core
Provides: pypi(py_cpuinfo)

%description python3
python3 components for the pypi-py_cpuinfo package.


%prep
%setup -q -n py-cpuinfo-8.0.0
cd %{_builddir}/py-cpuinfo-8.0.0
pushd ..
cp -a py-cpuinfo-8.0.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656397251
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-py_cpuinfo
cp %{_builddir}/py-cpuinfo-8.0.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-py_cpuinfo/bc698f64c398a3d4be6bdc320d55c75d60561abe
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cpuinfo

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-py_cpuinfo/bc698f64c398a3d4be6bdc320d55c75d60561abe

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
